### PR TITLE
Updated styles

### LINKED ISSUE #26: Improve styling by using stronger colours and monospaced font
Colours are very faint and this doesn't aid comparison. Stronger colours could make the differences be more visible. Try using font colours instead of just background colours.

Monospaced font would also aid comparison as all characters are of the same width.

### PR DESCRIPTION
**Pull request by fmalina**
Fixes #26

### CODE REVIEW

**Comment by zgrossbart** [comment]
Thank you so much for this update.  I think the new colors work really well on the compare page.  If you can make the text in the upper right of the main page align with the right-side compare field then I'd be really happy to take in this change.

Screen Shot 2019-03-25 at 8 42 01 AM

**Comment by fmalina** [comment]
Looks great!

**Comment by zgrossbart** [comment]
Sounds good.  Would you like to merge my PR into yours, or would you like me to merge your PR and then make changes on top of it?

**Comment by fmalina** [comment]
I don't have a preference. But I'd love if you could make this live and look at #27

**Comment by zgrossbart** [comment]
I have merged it in and made my changes on top of it.  Let me do a little more testing and I'll get it deployed soon.

I need to look more at #27.  I'm not sure about how that will work for larger JSON documents.  Let me think about it a bit more.

**Comment by zgrossbart** [comment]
This change is now deployed.  Thanks again for the awesome update.

**Pull request merged**
