### PR TITLE
Highlight children when parent is missing

### PR DESCRIPTION
**Pull request by SvenWerlen**
Same as [Highlight children when parent is missing](https://github.com/zgrossbart/jdd/pull/36) but I fixed.

### CODE REVIEW

**Comment by zgrossbart** [comment]
Can you please give me more of an overview of this change.  You say that you're highlighting children when a parent is missing.  What difference are you trying to show here?  What about parents of parents?  Can you come up with a simple case for this so we could add a unit test?

**Comment by SvenWerlen** [comment]
When an element is missing (left or right), its children should also be considered missing and be highlighted.
You can see it in your samples. "Alexander Skarsguard" is missing on the right, so "Generation Kill" and "True Blood" are also missing and highlighted. 
I don't know if that makes sense for you but the idea is similar to any text comparison tool
image

**Comment by zgrossbart** [comment]
So let's say I have a JSON object on the left with a property named `foo` and that property has 1,000 children.  If the JSON on the right doesn't have the `foo` property then would that mean I see 1,001 differences instead of one?

**Comment by SvenWerlen** [comment]
Yes, but I see the problem with that approach. 
In my case, I was more interested in highlighting those 1000 children and couldn't find a way to see it as 1 difference only.

**Comment by zgrossbart** [comment]
I'm a little worried about turning 1 difference into 1,001 or more.  This could result in too many differences to make sense of anything.

**Comment by SvenWerlen** [comment]
Sure, I understand. As I said, I reused your code only for the "highlight" so it's not a problem in my case. 
I'll close that pull request.

**Comment by zgrossbart** [comment]
Thank you for understanding.  I like the general idea of highlighting diffs in new ways.  If you come up with any other ideas please let me know.

**Comment by SvenWerlen** [comment]
Sure. Thanks.

**Pull request closed without merging**
