### PR TITLE
Exposed as a function so that multiple instances of it can be created wi…

### LINKED ISSUE #30: Corrupts the global namespace, hard to inject multiple instances in page

### PR DESCRIPTION
**Pull request by nitinsurana**
…th a different parent and do not interfere with each others' calcuation.

It also allows to re-initialize the UI with new dataset without refreshing the page
All qunit tests are working fine.
Fixes #30

### CODE REVIEW

**Comment by zgrossbart** [comment]
Thank you for this.  I'll take a closer look tomorrow. 

Do you think this should get merged into the master branch for the jsondiff.com website, or stay a separate project?

**Comment by nitinsurana** [comment]
It's a lot of change :-| I'm not sure, whether we should merge it or not. 
As far as functionality is concerned, jsondiff.com would remain unaffected with these changes. It may just become easier for someone to quickly inject this into their app.

**Comment by nitinsurana** [comment]
After giving it another thought - there's still a lot of coupling between UI and diffModel. Let's not merge at this point.

**Comment by zgrossbart** [comment]
I agree.  I'm going to close this PR.  Thank you.

**Pull request closed without merging**
